#!/bin/sh
# This defines a few aliased which can be used
# to add support for incremental builds in alibuild

# This function executes a command only if we are in a development package
# and the variant defined by ALIBUILD_BUILD_VARIANT is provided as first\
# argument.
function alibuild-variant-command() {
  # Check there is at least one argument
  [ $# -lt 2 ] && { echo "Usage: alibuild-variant-command <variant> <command>"; exit 1; }
  local _variant=$1
  shift
  [ -d $DEVEL_SOURCE ] && [ X$ALIBUILD_BUILD_VARIANT = X$_variant ] && { echo "Variant $_variant: $@" && eval "$@"; }
}

# This function will stop the build if the variant defined by ALIBUILD_BUILD_VARIANT
# matches the first argument.
function alibuild-variant-done() {
  # Check there is at least one argument
  [ $# -lt 1 ] && { echo "Usage: alibuild-variant-done <phase>"; exit 1; }
  local _phase=$1
  alibuild-variant-command $_phase exit 0
}
